---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  labels:
    title: pii-detection
    category: Custom
spec:
  extends:
    - name: extension-definition
  properties:
    language:
      type: string
      description: Two characters for the desired language in ISO_639-1 format
      default: "en"
    score_threshold:
      type: number
      description: The minimal detection score threshold
      default: 0.5
    action:
      type: string
      description: The action to do in case the request is consider it has sensitive data
      default: Reject
      enum:
        - Reject
        - Log
    server:
      type: string
      description: The name of the service where presidio is running
      default: presidio.default.svc
    server_url:
      type: string
      description: The url of the presidio server
      default: presidio_analyzer:3000
  required:
    - server_url
